---
# tasks file for running Nginx in Docker
#- name: Install Docker
#  package:
#    name: docker
#    state: present
#  tags:
#    - install-docker

#- name: Start Docker service
#  service:
#    name: docker
#    state: started
#    enabled: yes
#  tags:
#    - start-docker

- name: Pull Nginx Docker image
  docker_image:
    name: nginx
    tag: latest
    source: pull
  tags:
    - pull-nginx-image

- name: Run Nginx container
  docker_container:
    name: nginx
    image: nginx:latest
    state: started
    ports:
      - "80:80"
  tags:
    - run-nginx-container

- name: Ensure Nginx container is running
  docker_container:
    name: nginx
    state: started
  tags:
    - ensure-nginx-running
