---
# tasks file for running a webapp in Docker
- name: Install Docker
  package:
    name: docker
    state: present
  tags:
    - install-docker

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  tags:
    - start-docker

- name: Build Docker image for webapp
  docker_image:
    name: my-webapp
    build:
      path: "{{ target_dir }}"
    state: present
  tags:
    - build-webapp

- name: Run webapp container
  docker_container:
    name: webapp
    image: my-webapp:latest
    state: started
    ports:
      - "80:80"
  tags:
    - run-webapp-container

- name: Ensure webapp container is running
  docker_container:
    name: webapp
    state: started
  tags:
    - ensure-webapp-running
